import { ReactComponent as Heart } from "../assets/heart.svg";
import { ReactComponent as Brain } from "../assets/brain.svg";
import { ReactComponent as Cell } from "../assets/cell.svg";
import { ReactComponent as Biomechanics } from "../assets/biomechanics.svg";
import { ReactComponent as Publichealth } from "../assets/public-health.svg";
import { ReactComponent as Ai } from "../assets/ai.svg";
import { ReactComponent as Mobile } from "../assets/mobile.svg";
import { ReactComponent as Vision } from "../assets/vision.svg";
import { ReactComponent as Hardware } from "../assets/hardware.svg";
import { ReactComponent as Nlp } from "../assets/nlp.svg";
import { ReactComponent as Software } from "../assets/software.svg";
import { ReactComponent as Hci } from "../assets/hci.svg";
import { FaEnvelopeOpenText } from "react-icons/fa6";

export const HeartIcon = Heart;
export const BrainIcon = Brain;
export const CellIcon = Cell;
export const BiomechanicsIcon = Biomechanics;
export const PublichealthIcon = Publichealth;
export const AiIcon = Ai;
export const MobileIcon = Mobile;
export const VisionIcon = Vision;
export const HardwareIcon = Hardware;
export const NlpIcon = Nlp;
export const SoftwareIcon = Software;
export const HciIcon = Hci;
